version: "3.8"

services:
  mariadb:
    image: mariadb:10.9.3
    ports:
      - '${MYSQL_PORT}:3307'
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    command: mysqld --sql_mode="IGNORE_SPACE,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

  backend:
    depends_on:
      - mariadb
    container_name: backend-container
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/backend
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - ENVIROMENT

volumes:
  db-volume:
    name: ${DB_VOLUME_NAME}